// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddItemLogTag(arg1, arg2) {
  return window['go']['main']['App']['AddItemLogTag'](arg1, arg2);
}

export function AddLogItem(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddLogItem'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function AddTag(arg1) {
  return window['go']['main']['App']['AddTag'](arg1);
}

export function CreateLog(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateLog'](arg1, arg2, arg3);
}

export function DeleteLogItem(arg1) {
  return window['go']['main']['App']['DeleteLogItem'](arg1);
}

export function GetAnalytics() {
  return window['go']['main']['App']['GetAnalytics']();
}

export function GetLogItemsByDate(arg1) {
  return window['go']['main']['App']['GetLogItemsByDate'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function RemoveItemTag(arg1, arg2) {
  return window['go']['main']['App']['RemoveItemTag'](arg1, arg2);
}

export function SaveLogItem(arg1) {
  return window['go']['main']['App']['SaveLogItem'](arg1);
}
