// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';

export function AddItemLogTag(arg1:number,arg2:number):Promise<void>;

export function AddLogItem(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string):Promise<database.LogItem>;

export function AddTag(arg1:database.Tag):Promise<void>;

export function CreateLog(arg1:string,arg2:string,arg3:string):Promise<database.Log>;

export function DeleteLogItem(arg1:number):Promise<void>;

export function GetAnalytics():Promise<database.Analytics>;

export function GetLogItemsByDate(arg1:string):Promise<Array<database.LogItem>>;

export function GetLogs(arg1:string):Promise<Array<database.Log>>;

export function GetTags():Promise<Array<database.Tag>>;

export function RemoveItemTag(arg1:number,arg2:number):Promise<void>;

export function SaveLogItem(arg1:database.LogItem):Promise<database.LogItem>;
